name = "puppeteer"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]

browser = { binding = "BROWSER" }

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'screenshots'
preview_bucket_name = 'test-bucket'

[vars]
BUCKET_URL = "https://pub-04cd4de7299e4dbf942ccff55ae279d1.r2.dev"