name = "puppeteer"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'screenshots'
preview_bucket_name = 'screenshots'
