name = "puppeteer"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]

browser = { binding = "BROWSER" }

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'screenshots'
preview_bucket_name = 'test-bucket'